### ISSUE TITLE
Module Frames - TableTypes does not work

### ISSUE THREAD

**Issue by duarteguilherme** [acowley/Frames#115]
I am a data scientist familiar with languages such as R and python. 
I have been trying to learn haskell for two months (GHCi, version 8.0.2).

There is a module people employ to deal with frames in haskell similarly to common packages in those other languages (tidyverse in R and pandas in python).

The problem is: the common function for extracting data type for a csv is simply returning a message error:

    tableTypes "base" "base.csv"

    <interactive>:2:1: error:
        • No instance for (Show Language.Haskell.TH.Lib.DecsQ)
            arising from a use of ‘print’
        • In a stmt of an interactive GHCi command: print it

I cannot understand what this message means and I could not find any answer on Google. Could someone help me solve it?

**Comment by acowley** [comment]
Hello, the problem is that `tableTypes` is a TemplateHaskell macro: it generates Haskell code at compile time. You typically include it in a source file as in the tutorial and examples, and then use the definitions it produces. The tutorial includes some [example output](http://acowley.github.io/Frames/#orgbc7ce04) , or you can use GHCi to see what code it is generating for your table (bearing in mind that the variable names are not human-friendly):

You can run
```haskell
> :set -XQuasiQuotes -XTemplateHaskell
> import Language.Haskell.TH
> putStrLn $(tableTypes "base" "base.csv" >>= stringE . show . ppr_list)
```

The output is hard to read with the module prefixes, so we can clean that up a bit (though the spacing is still unappealing),

```haskell
> import Data.List
> import Data.Char
> let stripModule = until (\w -> length w == 1 || not ("." `isInfixOf` w)) (tail . dropWhile isAlpha)
> let onWords f xs = takeWhile isSpace xs ++ unwords (map f (words xs))
> putStrLn . unlines . map (onWords stripModule) $ lines $(tableTypes "base" "base.csv" >>= stringE . show . ppr_list)
```

I hope that helps!

**Comment by duarteguilherme** [comment]
It works. Thank you
