### ISSUE TITLE
Traversable instance for Frames

### ISSUE THREAD

**Issue by gbwey** [acowley/Frames#129]
Hi, is there any chance of adding a Traversable instance for Frame. It would be useful in conjunction with Control.Scanl (foldl).

**Comment by acowley** [comment]
I'm not immediately seeing a good way of adding it. I use the `foldl` package quite a bit, can you give me an example where the `Traversable` instance would pay off? The problem is that `Frame` itself is basically just a pure indexing function into something else. The fact that `Frame` isn't tied to any particular storage gives us quite a bit of flexibility to make things fast and compact in memory, but it makes this sort of thing harder. For instance, we might store an unboxed vector of `Int`s for one column, and a boxed vector of `Text` for another column, then provide a `Frame` that produces rows of something isomorphic to `(Int, Text)`.

To traverse a `Frame` would then seem to require that we traverse the various things that back the `Frame`, which seems like a dangerous thing to do from a performance standpoint (e.g. do we need to allocate new column stores for everything?). I think/hope that if you're aiming to do folds, then the existing pure indexing function meets your needs, but I'd be interested in seeing a case where it doesn't.

**Comment by gbwey** [comment]
I use in-memory frames almost exclusively but the use case would be lifting any Fold to a Scan. 
A simple example is prepending a frame with a running total column. 

FS.scan (postscanF @"tot" (FL.premap (V.rvalf #id) FL.sum)) (boxedFrame a)

-- adapted from Control.Scanl
postscanF :: forall s1 b us . (KnownSymbol s1)
  => FL.Fold (Rec V.ElField us) b -> FS.Scan (Rec V.ElField us) (Rec V.ElField ((s1 :-> b) ': us))
postscanF (FL.Fold step begin done) = FS.Scan (S.state . step') begin
  where
    step' a x = (V.Field @s1 b :& a, x')
      where
        x' = step x a
        b  = done x'

**Comment by acowley** [comment]
That is an excellent example use case, thank you. I don't think we have `Traversable` instances for all the `Vector` types we want to use, so it might not all fit together perfectly. One option would be to perform this operation via `pipes`, perhaps with a size hint.

I think I'd approach this by taking advantage of the fact that a `Frame` is just an indexing function. In your example, we probably would like to re-use the existing in-memory data rather than allocate new arrays only to copy the old data into them. So we generate the new column on its own, then construct a `Frame` whose indexing function indexes into the new column and the original `Frame`, then conses the two together. 

What we want is something riding atop `generateM` from `vector`, but I don't think we have the right pieces to make this perfectly smooth from a `Frames` API point of view yet. I think today you'd do something like `totVec <- generateM (frameLength origFrame) _`, then `Frame (frameLength origFrame) (liftA2 (:&) (totVec !) (frameRow origFrame))`.

Does that seem right?

**Comment by gbwey** [comment]
Yes, that sounds great.
