### ISSUE TITLE
How to define a new type of row ?

### ISSUE THREAD

**Issue by stla** [acowley/Frames#51]
Hello, 
In order to define a new record, I firstly define new types and lenses by hand:

```
import qualified Data.Vinyl.TypeLevel as DVT
import qualified Data.Vinyl as DV
import qualified Data.Vinyl.Functor as DVF 

type Foo = "foo" :-> Int
foo :: (Functor f0, RElem Foo rs0 (DVT.RIndex Foo rs0))  => (Int -> f0 Int) -> Record rs0 -> f0 (Record rs0)
foo = rlens (Proxy :: Proxy Foo)
foo' :: (Functor f0, Functor g0, RElem Foo rs0 (DVT.RIndex Foo rs0)) => (g0 Foo -> f0 (g0 Foo)) -> DV.Rec g0 rs0 -> f0 (DV.Rec g0 rs0)
foo' = rlens' (Proxy :: Proxy Foo)

type Baz = "baz" :-> Float
...
```

Then I define a record like this:

```
myRec :: Record '[Baz, Foo]
myRec = DVF.Identity 1.5 DV.:& DVF.Identity 3 DV.:& DV.RNil
```

Is there a more straightforward way? I believe there is one with [`RowGen`](https://hackage.haskell.org/package/Frames-0.1.4/docs/Frames-CSV.html#t:RowGen) but I don't understand how to use that, especially the last field (I'm not an eminent Haskell user).

**Comment by acowley** [comment]
This is a totally reasonable question as the library doesn't make this as obvious as it should, so thank you!

First, I'd write your example like so,

```haskell
type Foo = "foo" :-> Int
foo :: (Foo ∈ rs) => Lens' (Record rs) Int
foo = rlens (Proxy :: Proxy Foo)
foo' :: (Foo ∈ rs, Functor f) => Lens' (Rec f rs) (f Foo)
foo' = rlens' Proxy

type Baz = "baz" :-> Float
baz :: (Baz ∈ rs) => Lens' (Record rs) Float
baz = rlens (Proxy :: Proxy Baz)
baz' :: (Baz ∈ rs, Functor f) => Lens' (Rec f rs) (f Baz)
baz' = rlens' Proxy
```

You can get the `Lens'` type synonym from the [microlens](http://hackage.haskell.org/package/microlens) package if you don't want to pull in all of `lens`. The `∈` syntax is from `vinyl`. In case it's helpful: if you're using emacs, hit C-\ to enable the TeX input method, then type "\in" and the symbol will appear. 

But, to answer your question directly, here's how to do it using the `frames` machinery:

```haskell
declareColumn "Bar" ''Char

myRec :: Record '[Baz, Foo, Bar]
myRec = 1.5 &: 3 &: 'b' &: Nil

barTest :: Char
barTest = rget bar myRec
```

Unfortunately, I had to explicitly add an `import Frames.CSV (declareColumn)` to do that, so I will update the `Frames` module to export that splice since it is indeed useful.

**Comment by acowley** [comment]
I pushed to hackage, hopefully it will be on stackage soon, too. Also, please re-open the Issue if you still have any uncertainty!

**Comment by stla** [comment]
Thank you ! It works with `OverloadedStrings`. Nice !

**Comment by stla** [comment]
I've just written up a [blog post](http://stla.github.io/stlapblog/posts/HaskellFrames.html) about Frames. 

What do you think about the `Show` instance? It is very useful.

**Comment by acowley** [comment]
That's great, thank you for sharing!

That `Show` instance does look handy. I stayed away from adding one because I think what people want in terms of `show`ing will vary so much. To that end, I prefer writing specific `show`-like functions rather than relying on the type class. But that opens us up to the temptation to write orphan `Show` instances, and that has its own downsides. So maybe what you've done here is a good compromise to offer something out of the box, and diminish the temptation to write orphan instances. Let me chew on this for a bit, and let me know if you have any other thoughts. Usually I use `mapM_ print` or `Frames.Exploration.pipePreview` to print a few rows.

**Comment by stla** [comment]
This Show instance is inspired by the `dplyr` package for R.
```
> library(dplyr)
> iris_tbl <- as.tbl(iris)
> iris_tbl
# A tibble: 150 x 5
   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
          <dbl>       <dbl>        <dbl>       <dbl>  <fctr>
1           5.1         3.5          1.4         0.2  setosa
2           4.9         3.0          1.4         0.2  setosa
3           4.7         3.2          1.3         0.2  setosa
4           4.6         3.1          1.5         0.2  setosa
5           5.0         3.6          1.4         0.2  setosa
6           5.4         3.9          1.7         0.4  setosa
7           4.6         3.4          1.4         0.3  setosa
8           5.0         3.4          1.5         0.2  setosa
9           4.4         2.9          1.4         0.2  setosa
10          4.9         3.1          1.5         0.1  setosa
# ... with 140 more rows
```
Other very nice things in R are `summary`:
```
> summary(iris)
  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width          Species  
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100   setosa    :50  
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300   versicolor:50  
 Median :5.800   Median :3.000   Median :4.350   Median :1.300   virginica :50  
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199                  
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800                  
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500 
```
and `str` (structure):
```
> str(iris)
'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...
```

**Comment by acowley** [comment]
`summary` is something that's been on the "TODO" list since Day 1. Most of the pieces are there, it's just a matter of writing a class that provides a `fold` appropriate for each type.
