### ISSUE TITLE
Handle missing data with Bookkeeper

### ISSUE THREAD

**Issue by stites** [acowley/Frames#55]
From former experience with Frames, I recall having to wrap almost all of my column types with `Maybe` to handle missing data. I was wondering if something like the recently announced [bookkeeper](https://turingjump.com/blog/bookkeeper/) library might be able to address this issue. If you think it might be worth looking into, I'd love to take a shot at prototyping a Bookkeeper-backed Frames PR.

**Comment by acowley** [comment]
How do you see `bookkeeper` helping? I may be misunderstanding how it would fit together. My take on it is that I either drop rows with missing columns, or wrap those columns in `Maybe`. This lets me use column-based storage since every row is the same shape, and it lets me write a descriptive type for a `Frame` or streaming interface to a data file.

Before investing much time in code, can you give me an example of what you'd hope to see in terms of types? I'm not against the idea a priori, but I'd like to understand it better.

**Comment by stites** [comment]
> My take on it is that I either drop rows with missing columns, or wrap those columns in Maybe.

Yes, that would be the correct way to handle missing data in haskell — one thing that I miss from pandas, however, is the ability to not care about null-types until I have to. In essence: when exploring data, I like the idea of being able to pretend like my code is correct when it is not, and seeing all of the data.

~~Bookkeeper seems like it would give us the option to operate on malformed data~~ Nope, cancel that. I was thinking that Bookkeeper would allow for operating on data without knowing if the any of it was missing in a type-safe manner. Errors are still being thrown, so this cancels out the type-safety.

I guess my ideal version of Frames takes a user-given type, implicitly wraps it in a Maybe, then abstracts the Maybe away from the user so that they don't need to think about it for basic data exploration. Users coming from a data science backgrounds that are less comfortable in haskell wouldn't need to worry about Maybe-types.

**Comment by stites** [comment]
It sounds silly — I'm arguing against one extra fmap: `operate f listofMaybes = (fmap.fmap) f listofMaybes`. If I come up with something more concrete I'll let you know. Closing this now.

**Comment by acowley** [comment]
It's a valid point; see the inclusion of the `recMaybe` definition. I'm open to suggestions for making the `Maybe`s more transparent. If you can point to places where they really ugly things up, maybe we can at least improve the aesthetics.
