### ISSUE TITLE
Improve Double inference

### ISSUE THREAD

**Issue by codygman** [acowley/Frames#65]
## CSV
```
col_a,col_b,col_c
1,9,"1,000,000.00"
2,8,"300,000.00"
3,7,"0"
4,6,0
```
## Code
```haskell
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TemplateHaskell #-}
module TestDouble where

import Frames
import Frames.CSV
import Data.Vinyl
import Control.Monad.IO.Class
import qualified Pipes as P
import qualified Pipes.Prelude as P

tableTypes' rowGen "test.csv"
```

## expected type
```haskell
type Row =
  Record '["col_a" :-> Int, "col_b" :-> Int, "col_c" :-> Double]
```

## actual type
```haskell
type Row =
  Record '["col_a" :-> Int, "col_b" :-> Int, "col_c" :-> Bool]
```

**Comment by acowley** [comment]
Weird! The inference that a column whose only values are 0 and 1 is of type `Bool` is kind of iffy to begin with, but this is a nasty result.

Looking at the data, my guess was that `col_c` would get type `Text`, but somehow it's ignoring those first few rows for some reason, then seeing a single numeric value of 0 and so calling the whole column `Bool`. I'll have to look at the code to see what's happening.

**Comment by codygman** [comment]
@acowley Weird indeed. BTW I'm trying to figure out how to debug the inference. I want to try and infer types for a single line and was trying this:

```haskell
-- try testing inference on a single row
f :: forall s. (ColumnTypeable s) => s -> _
f s = map inferType . tokenizeRow defaultParser $ s

-- C:\Users\cody\Frames\src\Frames\TestDouble.hs:77:1: Could not deduce (ColumnTypeable b) …
--     from the context (ColumnTypeable s)
--       bound by the inferred type for `f': ColumnTypeable s => s -> [b]
--       at C:\Users\cody\Frames\src\Frames\TestDouble.hs:77:1-51
--     When checking that `f' has the specified type
--       f :: forall s b. ColumnTypeable s => s -> [b]
--     Probable cause: the inferred type is ambiguous
-- C:\Users\cody\Frames\src\Frames\TestDouble.hs:77:51: Couldn't match expected type `Text' with actual type `s' …
--       `s' is a rigid type variable bound by
--           the inferred type of f :: ColumnTypeable b => s -> [b]
--           at C:\Users\cody\Frames\src\Frames\TestDouble.hs:76:13
--     Relevant bindings include
--       s :: s
--         (bound at C:\Users\cody\Frames\src\Frames\TestDouble.hs:77:3)
--       f :: s -> [b]
--         (bound at C:\Users\cody\Frames\src\Frames\TestDouble.hs:77:1)
--     In the second argument of `($)', namely `s'
--     In the expression: map inferType . tokenizeRow defaultParser $ s
```

I was thinking I could just generate the `Q Type` for each `a` and then visually inspect it? Or is this too low down in the "lattice" (I think that's what is meant by lattice but I'm just going by what I've learned thus far) where there isn't information on how to resolve the final type.

Thanks!

**Comment by codygman** [comment]
I assumed as soon as the double type was inferred that inference would be done since it is the most specific type, is that not how it works @acowley?

**Comment by acowley** [comment]
Interestingly, it works in the opposite way: we have to pick the greatest lower bound sufficient to represent every row we look at for a particular column. Typically this means falling back to `Text`. For example, if a particular column contains `[3.2, 1, "two"]`, then we give it a type of `Text` because we need that to represent each of those values at the same type.

**Comment by codygman** [comment]
I'm mainly struggling with how to take specific functions such as parse' or lubtypes and use them in ghci by specifying the types/type constraints.

Can you order any examples or advice on how to do this or otherwise debug this problem?

**Comment by acowley** [comment]
It needs improvement, but here's what I did in a repl when working on this (note that I added `foldCoRec` and `parsedTypeRep` in that commit):

```haskell
> let cs1 = (map inferType (tokenizeRow defaultParser "3,7,\"0\"") :: [Columns])
> let cs2 = (map inferType (tokenizeRow defaultParser "2,8,\"300,000.00\"") :: [Columns])
> let csm = zipWith (<>) cs1 cs2
> map (foldCoRec parsedTypeRep) csm
[Definitely Int,Definitely Int,Possibly Text]
> map (foldCoRec parsedTypeRep) cs1
[Definitely Int,Definitely Int,Definitely Bool]
> map (foldCoRec parsedTypeRep) cs2
[Definitely Int,Definitely Int,Definitely Double]
```

Which is a different failure mode than we were debugging because that example used the wrong parser, but it was helpful to see how things flowed through the functions. Note that the `Monoid` instance is used as an API to `lubTypes`.

You might also want to look at the spec testing I added recently. I added a case for this bug on the linked commit. It's marginally helpful to just add a CSV to the `toml` file with an empty string for the `generated` field. I say "marginally" because, at least on my machine, the output of `stack test :spec` requires some massaging to be readable. Specifically, I had to replace newline characters with actual newlines, and the fancy `RElem` syntax came out wrong in my shell.
