### ISSUE TITLE
Use types default value instead of not parsing row

### ISSUE THREAD

**Issue by codygman** [acowley/Frames#72]
```
col_a,col_b
"0","x"
"2","x"
"1",x"
,"x"
"0","x"
```

The current behavior returns:

```
{col_a :-> False, col_b :-> "x"}
{col_a :-> True, col_b :-> "x"}
{col_a :-> False, col_b :-> "x"}
```
I'd like a way to get:
```
{col_a :-> 0, col_b :-> "x"}
{col_a :-> 2, col_b :-> "x"}
{col_a :-> 1, col_b :-> "x"}
{col_a :-> 0, col_b :-> "x"} -- this one was blank and defaulted according to type int
{col_a :-> 0, col_b :-> "x"}
```

I tried modifying coRecToRec to use mempty instead of returning a maybe value but to be honest I'm just barely understanding how it works and it's quite late, so off to sleep ;)

**Comment by acowley** [comment]
Can you clarify your expected result? It looks the same as the one labeled as current behavior, but neither looks right to me given the presence of a 2 in `col_a`.

**Comment by codygman** [comment]
Updated the expected, the actual is still a bit off.

**Comment by codygman** [comment]
Correction, if memory serves correctly the actual result is right. 2 rows well fail to parse since they can't be made into true or false.

**Comment by acowley** [comment]
The way the library is set up, you should be able to use `readTableMaybe`, and then map a function over the data frame that takes each `Rec Maybe rs` to a `Record rs` using a combination of `rmap` from `vinyl` and `mapMethod` from `Frames`.

**Comment by codygman** [comment]
I think that will work, but the csv's I'm working with have 10~ million
rows so I'd like to avoid the extra loop over the data.

That's why I was focusing on returning the CoRec with a default instead of
maybe. Is this approach possible? I'll try using the readTableMaybe
approach as well.

**Comment by acowley** [comment]
If you apply that default logic on the `Producer` coming from `readTableMaybe` then there is no extra traversal. Lunch is free! 😄

**Comment by codygman** [comment]
Free lunch is always good :100: 

So here's my attempt thus far at doing the above, though I don't yet fully understand the core Record/Rec types and I'm unsure which constraints mapMethod needs or what exactly the mapMethod type signature means:

```
unholyOrig :: Rec First '[MyString, MyInt, MyBool] -> Maybe (Record '[MyString, MyInt, MyBool])
unholyOrig holy = recMaybe (rmap getFirst (rapply rmapFunc holy))
    where rmapFunc = (rmap (\s -> Lift $ flip (<>) $ s) def)

-- unholyRows :: Rec Maybe '[MyString, MyInt, MyBool]
-- unholyRows = mapMethod [pr|Default|] unholy holyRows

-- unholyDesired :: forall rs. (AsVinyl rs) => Rec Maybe rs -> Record rs
-- unholyDesired mRec = _ mRec
-- demo/MissingData.hs:61:22: Warning: …
--     Found hole ‘_’ with type: Rec Maybe rs -> Record rs
--     Where: ‘rs’ is a rigid type variable bound by
--                 the type signature for
--                   unholyDesired :: AsVinyl rs => Rec Maybe rs -> Record rs
--                 at /home/cody/source/Frames/demo/MissingData.hs:60:25
--     Relevant bindings include
--       mRec :: Rec Maybe rs
--         (bound at /home/cody/source/Frames/demo/MissingData.hs:61:15)
--       unholyDesired :: Rec Maybe rs -> Record rs
--         (bound at /home/cody/source/Frames/demo/MissingData.hs:61:1)
--     In the expression: _
--     In the expression: _ mRec
--     In an equation for ‘unholyDesired’: unholyDesired mRec = _ mRec

-- unholyDesired :: forall rs. (AsVinyl rs) => Rec Maybe rs -> Record rs
-- unholyDesired mRec = rmap _ mRec
-- demo/MissingData.hs:78:27: Warning: …
--     Found hole ‘_’ with type: Maybe x -> Identity x
--     Where: ‘x’ is a rigid type variable bound by
--                a type expected by the context: Maybe x -> Identity x
--                at /home/cody/source/Frames/demo/MissingData.hs:78:22
--     Relevant bindings include
--       mRec :: Rec Maybe rs
--         (bound at /home/cody/source/Frames/demo/MissingData.hs:78:15)
--       unholyDesired :: Rec Maybe rs -> Record rs
--         (bound at /home/cody/source/Frames/demo/MissingData.hs:78:1)
--     In the first argument of ‘rmap’, namely ‘_’
--     In the expression: rmap _ mRec
--     In an equation for ‘unholyDesired’:
--         unholyDesired mRec = rmap _ mRec

unholyDesired :: forall rs. (AsVinyl rs) => Rec Maybe rs -> Record rs
unholyDesired mRec = rmap f mRec
  where f singleRecord = case singleRecord of
          Just singleRecord' -> Identity singleRecord'
          Nothing -> error "idk what goes here"

unholyDesired' :: Rec Maybe '[MyString,MyInt,MyBool] -> Record '[MyString,MyInt,MyBool]
unholyDesired' mRec = rmap f mRec
  where f singleRecord = case singleRecord of
          Just singleRecord' -> Identity singleRecord'
          Nothing -> error "idk what goes here"


-- wrong approach here I think
-- recMaybeProducerToRecProducer :: Monad m => P.Producer (Rec Maybe rs) m () -> P.Producer (Record rs) m ()
-- recMaybeProducerToRecProducer producer = producer P.>-> _

-- also wrong appraoch I think
-- useUnholyDesired = readTableMaybeOpt defaultParser "test.csv" >>= \producer -> P.runEffect $ producer _ unholyDesired

-- iThinkIHaveIt = mapMethod [pr|Default|] unholyDesired holyRows
-- demo/MissingData.hs:111:17: No instance for (Default Bool) arising from a use of ‘mapMethod’ …
--     In the expression:
--       mapMethod (Proxy :: Proxy Default) unholyDesired holyRows
--     In an equation for ‘iThinkIHaveIt’:
--         iThinkIHaveIt
--           = mapMethod (Proxy :: Proxy Default) unholyDesired holyRows
-- demo/MissingData.hs:111:41: Couldn't match type ‘a’ with ‘Record rs0’ …
--       ‘a’ is a rigid type variable bound by
--           a type expected by the context: Default a => a -> a
--           at /home/cody/source/Frames/demo/MissingData.hs:111:17
--     Expected type: a -> a
--       Actual type: Rec Maybe rs0 -> Record rs0
--     In the second argument of ‘mapMethod’, namely ‘unholyDesired’
--     In the expression:
--       mapMethod (Proxy :: Proxy Default) unholyDesired holyRows
-- Compilation failed.

iThinkIHaveIt = mapMethod [pr|Default|] unholyDesired' holyRows
-- I thought specifying unholyDesired more would help. I think it did a bit, but I'm confused by the error about it looking for a (Default Bool) instance
```

Using typed holes I got that far, but I'm not sure how to apply my `Rec Maybe rs -> Record rs` function now. I have a feeling I'm supposed to use `mapMethod` but I'm stuck on an error where a (Default Bool) instance is being asked for. 

Perhaps my struggles and the answers to correcting them can be useful for others as well and help improve pedagogy here.

**Comment by acowley** [comment]
I tweaked the MissingData demo to directly show how to do this [here](https://github.com/acowley/Frames/blob/c6a2334fd826843e8e814e8fb2681996e1c90fec/demo/MissingData.hs#L58)

All the method magic really happens in the `Default` instance for `Rec` that uses `reifyDict`. The `reifyDict` function is very similar to `mapMethod`: the only difference is that it is not a function applied to an element of a `Rec`, instead a new value is synthesized from only the satisfied type class constraint.

The plumbing is similar to what was already there, but it is perhaps spelled out more nicely now. The `def` `Rec` value gives us things to slot in to missing columns, so we take the `Rec Maybe ts` we got from the file, turn it into a `Rec First ts` to set up the `Monoid` instance we want, then combine each incoming row of type `Rec First ts` with another `Rec First ts` provided by the `def` value. After that we unwrap the `First`, and finally the `Maybe`. The value we constructed with `def` has a type that is too large (we know every value is a `Just` even though the type says that we do not know that), but enlarging that type lets us combine it with the rows we read from the data file. Based on that, we use the partial `fromJust` helper to finish the unwrapping.

The complicated bit in the middle is the use of `rapply` and `Lift`. The `rapply` function gives us a way of applying a record of functions to a record of values. The `Lift` part there is because those functions are something like natural transformations in that they have a type `f a -> g a` where the `a` there is coming from the field type index of the record types, and the `f` and `g` are the functor types from the argument `Rec` and the resulting `Rec`. Whereas a natural transformation would quantify over all `a`s, we instead provide `rapply` with a list of functions at particular `a`s. Which `a`s? The ones corresponding to the fields of our record.

It might help to look at this in the REPL:

```haskell
> :t rmap (Lift . flip (<>)) (def :: Rec First (RecordColumns Row))
rmap (Lift . flip (<>)) (def :: Rec First (RecordColumns Row))
  :: Rec (Lift (->) First First) '["col_a" :-> Int, "col_b" :-> Text]
```

So our incantation there gives us a `Rec` of functions that corresponds to `[First ("col_a" :-> Int) -> First ("col_a" :-> Int), First ("col_b" :-> Text) -> First ("col_b" :-> Text)]`. And that is a record that `rapply` can apply to a `Rec First (RecordColumns Row)` to give us another value of type `Rec First (RecordColumns Row)`.

(Recall that `RecordColumns` is a type function that just returns the list of types that index a `Record` type: `RecordColumns (Record ts) = ts`)

**Comment by codygman** [comment]
Thank you for the detailed information and the complete code example. Defaults by column names are nice, but not when you have 200 columns you need to define default instances for.

I desire being able to set a default based on the type of the column and don't care about column names in many instances.

Later I'll try to digest your explanation and implement what I need, but let me know if it's not possible ;)

Thanks!

**Comment by acowley** [comment]
@codygman It's written like that just to fit with the existing module without introducing overlaps. You can always write,

```haskell
instance Default (s :-> Int) where def = 0
```

**Comment by codygman** [comment]
@acowley Thanks again... Goodness that was simple, I feel silly.

**Comment by acowley** [comment]
Not at all! I originally wrote it that way (`s :-> Int`) because I knew you wanted that, but hit the overlaps and forgot to make a not of it. A nice thing here, I think, is that you can just about get the best of all worlds with specific and generic defaults.
