### ISSUE TITLE
Consider using Cassava for csv parsing

### ISSUE THREAD

**Issue by codygman** [acowley/Frames#75]
I'm sure this was something you were going to consider eventually, but thought I'd get the ball rolling since I ran into some problems trying to play with this dataset:

https://data.texas.gov/Business-and-Economy/DIR-Cooperative-Contract-Sales-Data-Fiscal-2010-to/w4x7-gfja

I believe the handling of csvs chokes on newlines not meaning "one row" in Frames current csv parsing scheme, but I tried it out in Cassava and everything parsed fine.

I thought of two different approaches:

1. Make a version of cassava that works with frames and update functions like [decodeWithP](https://github.com/hvr/cassava/blob/545b86d60276c51ec29681f1917f1e5fb9b67c54/Data/Csv/Incremental.hs#L285).
2. Generate Named Record Instances and parse as is already done in cassava but then output in a Vinyl record.

EDIT: Perhaps we can be really lazy and just use the [record parser](https://github.com/hvr/cassava/blob/545b86d60276c51ec29681f1917f1e5fb9b67c54/Data/Csv/Parser.hs#L138) with the current Frames csv implementation.

**Comment by acowley** [comment]
I'll take a look at that data set. I originally stopped using cassava because I had a string of cases where it didn't parse my data without a lot of massaging.

**Comment by cumber** [comment]
I just ran into a similar issue with a dataset that had a long text field where some values contained 
newlines. `tableTypes` just produced a data set with only 1 field (rather than the 20 or so the CSV file actually contained).

If the csv-parsing just doesn't intend to support multi-line fields/rows, it would be nice if the behaviour was some sort of error when the contents of the file don't appear to match the header, rather than just dropping columns. That would have helped me get to the required workaround a lot sooner (pre-process with a tool that does understand newlines in fields to drop the long text column)

**Comment by acowley** [comment]
@cumber I say we nip this in the bud from both sides! I have a [package](https://github.com/acowley/Frames-dsv) almost ready for release that provides CSV parsing using `hw-dsv`, and I'd like to do better about having the built-in parser emit an error message when possible as you suggest. Can you provide me with a data file that exhibits the problem you encountered so that I can add it as a test case for both parsing approaches? I'd like to make sure I'm addressing specifically what you encountered.

**Comment by cumber** [comment]
@acowley I can't release any of the actual data files I'm using, but this CSV shows the problem I encountered:

```
RowNum,Description,X,Y
1,"simple",10,10
2,"""quoted""",20,20
3,"multi
line
text
field",30,30
4,"simple again",40,40
```

After using `tableTypes "Row" "multiline.csv"` I get

```
λ :info Row
type Row = Record '[RowNum]
```

I think what's happening is that it doesn't recognise any columns that don't appear in every row, and the lines containing `line`, `text`, etc look like they contain only a single column when you try to parse them as independent CSV rows.

If I delete the newlines from the multline field, then `tableTypes` instead produces:

```
λ :info Row
type Row = Record '[RowNum, Description, X, Y]
```

**Comment by acowley** [comment]
Thank you for this! I've gone ahead and added a check, and associated [test](https://github.com/acowley/Frames/blob/master/test/Spec.hs#L195), to `Frames` so it blows up if the data read disagrees in column count with the header, and I've published the [Frames-dsv](https://hackage.haskell.org/package/Frames-dsv) package that has a matching [test](https://github.com/acowley/Frames-dsv/blob/master/test/Spec.hs) to show it successfully parsing this example.

In the event that `Frames-dsv` doesn't yet expose enough flexibility, we can expand it to meet needs. It should now also be possible for anyone to write a package supplying a parser for whatever format they're working with.
